#!/usr/bin/env python
import h5py
import sys,os
import shutil
import numpy as np
import pandas as pd

filename=sys.argv[1]
filetag=".".join(filename.split(".")[:-1])
print("Initial file name ",filename)
print("Initial file tag ",filetag)
cwd = os.getcwd()

dicto=["E1","dip1"]

################################################################
## extract data from full h5 file and create smaller h5 file  ##
################################################################

directory_name=cwd
with h5py.File(directory_name+"/"+filetag+".h5","r") as f:
    dat=[]
    E1=f['SFS_ENERGIES'][:]                                 # energies corresponding to the lasts "RASSI State 1 Total energy:"
    dat.append(E1)
    dip1=f['SFS_EDIPMOM'][:]
    dat.append(dip1)
print("Extracted data re-compressed in ",filetag+".ExtractedData.h5")
with h5py.File(directory_name+"/"+filetag+".ExtractedData.h5","w") as f:
    for i,j in zip(dicto,dat):
        dset=f.create_dataset(i,j.shape,data=j,compression="gzip",compression_opts=9)

################################################################
## creating .dat files in data_dir                            ##
################################################################

filename=filetag+".ExtractedData.h5"
filetag=".".join(filename.split(".")[:-1])
print("Data will be extracted from ",filename)
data_dir="datafiles_"+filetag
print("Dat files will be put in {}".format(data_dir))
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

cwd = os.getcwd()

dicto=["E1","dip1"]

print_header=False
print_index=False

directory_name = cwd
with h5py.File(directory_name+"/"+filetag+".h5","r") as f:
    E1=f['E1'][:]
    dip1=f['dip1'][:]
NStates=len(E1)//2
pd.options.display.float_format = '{:,.16f}'.format
with open(cwd+'/'+data_dir+'/E1_n1.dat', "w") as g:
    df=pd.DataFrame({'E1':E1-E1[0]})
    g.write(df.to_string(header=print_header,index=print_index))
pd.options.display.float_format = '{:,.16E}'.format
with open(cwd+'/'+data_dir+'/dip1_n1.dat', "w") as g:
    df=pd.DataFrame({'dip1_x':dip1[0,0,:],'dip1_y':dip1[1,0,:],'dip1_z':dip1[2,0,:],})
    g.write(df.to_string(header=print_header,index=print_index))
